### ISSUE TITLE
SchemaForGameResultModel "JSON integer 4294967295 is too large or small for an Int32"

### ISSUE THREAD

**Issue by nfMalde** [babelshift/Steam.Models#1]
Hi,
Im Importing via SteamWebApi2 the Achievements for Games. At some Achievements a get the Exception  that "JSON integer 4294967295 is too large or small for an Int32".  For the Property "DefaultValue" at SchemaForGameResultModel. Changing DefaultValue from int to long should fix that. For now im catching the exception but unfurnatly im not able to import this achievement as long this exception getting thrown.

![steammodelserror](https://cloud.githubusercontent.com/assets/5366984/21164515/cc248e10-c199-11e6-8b4b-a7595e56983e.png)

It happens at APP ID 240.

Best,

Malte

**Comment by babelshift** [comment]
Thanks. I'll check it out soon.

**Comment by babelshift** [comment]
Should be fixed on commit 5327d511eb2bf1d653527a779b3e040f2733bd08 and the latest nuget package. Please let me know.
