### ISSUE TITLE
data type problem

### ISSUE THREAD

**Issue by dFxed** [babelshift/Steam.Models#7]
I think that steam updated their model to match new datatype on gameuserstats
If you do this request, you can see that some values are float.

http://api.steampowered.com/ISteamUserStats/GetUserStatsForGame/v0002/?appid=204300&key=YOUR_STEAM_DEV_KEY&steamid=76561197960291106

please update this Library and depending projects.
proposal of comit : 
`namespace Steam.Models.SteamPlayer
{
    public class UserStatModel
    {
        public string Name { get; set; }

        public double Value { get; set; }
    }
}`

**Comment by babelshift** [comment]
Fixed on commit 20025454da4b02d59b1a37725a8bf1dd0d1f13f9.

**Comment by dFxed** [comment]
Issue is still open.

got this stacktrace with latest repo : 

   à Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   à Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   à Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   à SteamWebAPI2.Utilities.SteamWebRequest.<SendWebRequestAsync>d__6`1.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à SteamWebAPI2.Utilities.SteamWebRequest.<GetAsync>d__4`1.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à SteamWebAPI2.Utilities.SteamWebInterface.<GetAsync>d__5`1.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à SteamWebAPI2.Interfaces.SteamUserStats.<GetUserStatsForGameAsync>d__7.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à TestScreenshot.Form1.<GetPlayerHours>d__18.MoveNext() dans C:\Users\david\Desktop\D\Direct3DHook-master\TestScreenshot\Form1.cs:ligne 295
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à TestScreenshot.Form1.<SequenceRequests>d__22.MoveNext() dans C:\Users\david\Desktop\D\Direct3DHook-master\TestScreenshot\Form1.cs:ligne 436

Input string '6.3046398162841797' is not a valid integer. Path 'playerstats.stats[41].value', line 1, position 3253.

I've double checked Steam.Models.SteamPlayer.UserStatModel.Value definition, and it is set to double, so I don't get what is wrong. May be you can succeed.

**Comment by dFxed** [comment]
I think I've figured it.

may it be : 
namespace SteamWebAPI2.Models
internal class UserStat
        [JsonProperty("value")]
        public int Value { get; set; }

Datatype may be wrong there too ...

After testings, it fixes the bug.

**Comment by babelshift** [comment]
Please try the latest nuget package 4.0.5. Thanks.

**Comment by dFxed** [comment]
Solved
