### ISSUE TITLE
Pre-release Version Suffix Doesn't Comply with SemVer 2.0.0

### ISSUE THREAD

**Issue by MarkKoz** [babelshift/Steam.Models#9]
NuGet doesn't seem to like the version suffix appended to the NuGet package. Semantic Versioning 2.0.0 (which NuGet now supports) [specification 9](https://semver.org/#spec-item-9) disallows leading zeros in the pre-release version. 

> Numeric identifiers MUST NOT include leading zeroes.

This caused the packing to fail for me. The culprit is this line in `default.ps1`:

```powershell
$version = "{0:D5}" -f [convert]::ToInt32($version, 10)
```
Removing the precision specifier of 5 in `0:D5` will remove the leading zeros. I'm not too familiar with the whole build process so I'll leave it up to someone else to decide on an appropriate solution.

**Comment by babelshift** [comment]
Thanks. I'll check it out today/tomorrow.

**Comment by babelshift** [comment]
Fixed on 44500a9e07997a8708e3fd6332cb970a83b87e5d.
